server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    # fetchRegistry、registerWithEureka 表示是个eureka server.
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/